version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=store-web-db
      - POSTGRES_USER=admindb
      - POSTGRES_PASSWORD=4dm1nSys.
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=4dm1nSys.
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=store-web-db
      - MYSQL_USER=
      - MYSQL_ROOT_PASSWORD=4dm1nSys.
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=4dm1nSys.
      - PMA_HOST=mysql
    ports:
      - 8080:80
